"""
CyphEV — Train lightweight models and export as C headers for ESP32.

Usage:
    pip install numpy pandas scikit-learn xgboost lightgbm emlearn
    python train_and_export.py

Outputs:
    models/  — pickled sklearn models + scalers
    esp32_firmware/models/  — C header files for ESP32
"""

import os, sys, warnings, json
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import Lasso, Ridge, RidgeCV, LassoCV
from sklearn.model_selection import train_test_split, GroupKFold
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import xgboost as xgb

warnings.filterwarnings("ignore")

# ── Paths ────────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
BMW_DIR = ROOT / "03 SoC + Range Prediction [Benchmark]" / "BMW_i3_Dataset"
NASA_DIR = ROOT / "04 SoH + RUL Prediction [Benchmark]" / "NASA_Cleaned_Dataset"
OUT_DIR = Path(__file__).resolve().parent / "training_metadata"
HEADER_DIR = Path(__file__).resolve().parent / "esp32_firmware" / "main" / "models"

OUT_DIR.mkdir(parents=True, exist_ok=True)
HEADER_DIR.mkdir(parents=True, exist_ok=True)


# ═══════════════════════════════════════════════════════════════════════════
#  UTILITIES
# ═══════════════════════════════════════════════════════════════════════════

def _parse_impedance(val):
    """Parse impedance value, handling complex number strings.
    Re and Rct are real-valued quantities; complex strings use .real part."""
    try:
        return float(val)
    except (ValueError, TypeError):
        try:
            c = complex(val)
            return c.real
        except (ValueError, TypeError):
            return np.nan


def find_col(df, pattern):
    """Find a column by substring match (handles encoding issues in BMW CSV)."""
    for c in df.columns:
        if pattern.lower() in c.lower():
            return c
    return None


def export_linear_model_header(name, weights, bias, scaler_mean, scaler_scale,
                                feature_names, filename, poly_powers=None):
    """Export a linear model (Ridge/Lasso) as a C header file.

    If poly_powers is provided, the model uses polynomial features.
    poly_powers is a 2D array of shape (n_poly_features, n_base_features)
    representing the exponent of each base feature for each poly term.
    """
    n_features = len(weights)
    n_base = len(scaler_mean)

    lines = []
    lines.append(f"// Auto-generated by train_and_export.py")
    lines.append(f"// Model: {name}")
    lines.append(f"#ifndef MODEL_{name.upper()}_H")
    lines.append(f"#define MODEL_{name.upper()}_H")
    lines.append(f"")
    lines.append(f"#define {name.upper()}_N_BASE_FEATURES {n_base}")
    lines.append(f"#define {name.upper()}_N_FEATURES {n_features}")
    lines.append(f"")

    # Scaler parameters (for base features)
    lines.append(f"static const float {name}_scaler_mean[{n_base}] = {{")
    lines.append(f"  {', '.join(f'{v:.8f}f' for v in scaler_mean)}")
    lines.append(f"}};")
    lines.append(f"static const float {name}_scaler_scale[{n_base}] = {{")
    lines.append(f"  {', '.join(f'{v:.8f}f' for v in scaler_scale)}")
    lines.append(f"}};")
    lines.append(f"")

    # Model weights and bias
    lines.append(f"static const float {name}_weights[{n_features}] = {{")
    # Split into lines of 8 for readability
    for i in range(0, n_features, 8):
        chunk = weights[i:i+8]
        lines.append(f"  {', '.join(f'{v:.8f}f' for v in chunk)},")
    lines.append(f"}};")
    lines.append(f"static const float {name}_bias = {bias:.8f}f;")
    lines.append(f"")

    # Polynomial powers if applicable
    if poly_powers is not None:
        n_poly = poly_powers.shape[0]
        n_base_poly = poly_powers.shape[1]
        lines.append(f"#define {name.upper()}_USE_POLY 1")
        lines.append(f"#define {name.upper()}_N_POLY_BASE {n_base_poly}")
        lines.append(f"// Polynomial exponent matrix: [{n_poly}][{n_base_poly}]")
        lines.append(f"static const uint8_t {name}_poly_powers[{n_poly}][{n_base_poly}] = {{")
        for row in poly_powers:
            lines.append(f"  {{{', '.join(str(int(v)) for v in row)}}},")
        lines.append(f"}};")
    else:
        lines.append(f"#define {name.upper()}_USE_POLY 0")

    lines.append(f"")

    # Inline predict function
    lines.append(f"static inline float {name}_predict(const float raw_features[{n_base}]) {{")
    lines.append(f"  // 1. Scale base features")
    lines.append(f"  float scaled[{n_base}];")
    lines.append(f"  for (int i = 0; i < {n_base}; i++) {{")
    lines.append(f"    scaled[i] = (raw_features[i] - {name}_scaler_mean[i]) / {name}_scaler_scale[i];")
    lines.append(f"  }}")
    lines.append(f"")

    if poly_powers is not None:
        n_poly = poly_powers.shape[0]
        n_base_poly = poly_powers.shape[1]
        lines.append(f"  // 2. Compute polynomial features")
        lines.append(f"  float poly[{n_poly}];")
        lines.append(f"  for (int i = 0; i < {n_poly}; i++) {{")
        lines.append(f"    poly[i] = 1.0f;")
        lines.append(f"    for (int j = 0; j < {n_base_poly}; j++) {{")
        lines.append(f"      for (int p = 0; p < {name}_poly_powers[i][j]; p++) {{")
        lines.append(f"        poly[i] *= scaled[j];")  # poly base indices = first n_base_poly of scaled
        lines.append(f"      }}")
        lines.append(f"    }}")
        lines.append(f"  }}")
        lines.append(f"")
        lines.append(f"  // 3. Dot product")
        lines.append(f"  float result = {name}_bias;")
        lines.append(f"  for (int i = 0; i < {n_features}; i++) {{")
        lines.append(f"    result += {name}_weights[i] * poly[i];")
        lines.append(f"  }}")
    else:
        lines.append(f"  // 2. Dot product")
        lines.append(f"  float result = {name}_bias;")
        lines.append(f"  for (int i = 0; i < {n_features}; i++) {{")
        lines.append(f"    result += {name}_weights[i] * scaled[i];")
        lines.append(f"  }}")

    lines.append(f"  return result;")
    lines.append(f"}}")
    lines.append(f"")
    lines.append(f"#endif // MODEL_{name.upper()}_H")

    filepath = HEADER_DIR / filename
    filepath.write_text("\n".join(lines))
    print(f"  -> Exported {filepath}")


def export_xgb_emlearn_header(name, model, filename):
    """Export XGBoost model using emlearn (tree ensemble -> C code)."""
    try:
        import emlearn
        cmodel = emlearn.convert(model, method='inline')
        filepath = HEADER_DIR / filename
        cmodel.save(file=str(filepath), name=name)
        print(f"  -> Exported {filepath} (via emlearn)")
        return True
    except ImportError:
        print("  !! emlearn not installed, falling back to manual export")
        return False


def export_xgb_manual_header(name, model, scaler_mean, scaler_scale, n_base, filename):
    """Fallback: export XGBoost as a JSON ensemble and write a C header with
    a simple tree-walk interpreter. Works without emlearn."""

    # Get trees as text
    booster = model.get_booster()
    trees_json = booster.get_dump(dump_format='json')

    import json as json_mod

    # Parse all trees into flat node arrays
    all_nodes = []  # list of trees, each tree = list of (feature_idx, threshold, left, right, leaf_value)

    def flatten_tree(node, nodes_list):
        idx = len(nodes_list)
        if 'leaf' in node:
            nodes_list.append((-1, node['leaf'], -1, -1))
            return idx
        else:
            # placeholder
            nodes_list.append(None)
            feat = int(node['split'][1:]) if node['split'].startswith('f') else int(node['split'])
            threshold = float(node['split_condition'])
            left_idx = flatten_tree(node['children'][0], nodes_list)
            right_idx = flatten_tree(node['children'][1], nodes_list)
            nodes_list[idx] = (feat, threshold, left_idx, right_idx)
            return idx

    for tree_str in trees_json:
        tree_dict = json_mod.loads(tree_str)
        nodes = []
        flatten_tree(tree_dict, nodes)
        all_nodes.append(nodes)

    n_trees = len(all_nodes)
    # XGBoost 2.0+ auto-learns base_score (returns None from get_params).
    # Read the actual learned value from the booster config.
    try:
        import json as _json
        _cfg = _json.loads(model.get_booster().save_config())
        _bs_str = _cfg['learner']['learner_model_param']['base_score']
        # May be a string like "[7.0148056E1]" — strip brackets
        _bs_str = str(_bs_str).strip('[]')
        base_score = float(_bs_str)
    except Exception:
        bs = model.get_params().get('base_score', None)
        base_score = float(bs) if bs is not None else 0.5

    lines = []
    lines.append(f"// Auto-generated XGBoost model for ESP32")
    lines.append(f"// Model: {name}")
    lines.append(f"#ifndef MODEL_{name.upper()}_H")
    lines.append(f"#define MODEL_{name.upper()}_H")
    lines.append(f"")
    lines.append(f"#define {name.upper()}_N_BASE_FEATURES {n_base}")
    lines.append(f"#define {name.upper()}_N_TREES {n_trees}")
    lines.append(f"#define {name.upper()}_BASE_SCORE {base_score:.6f}f")
    lines.append(f"")

    # Scaler
    lines.append(f"static const float {name}_scaler_mean[{n_base}] = {{")
    lines.append(f"  {', '.join(f'{v:.8f}f' for v in scaler_mean)}")
    lines.append(f"}};")
    lines.append(f"static const float {name}_scaler_scale[{n_base}] = {{")
    lines.append(f"  {', '.join(f'{v:.8f}f' for v in scaler_scale)}")
    lines.append(f"}};")
    lines.append(f"")

    # Emit each tree as a function
    for t_idx, nodes in enumerate(all_nodes):
        lines.append(f"static inline float {name}_tree{t_idx}(const float *f) {{")
        # iterative tree walk
        lines.append(f"  int node = 0;")
        lines.append(f"  while (1) {{")
        lines.append(f"    switch (node) {{")
        for n_idx, node in enumerate(nodes):
            feat, thresh_or_leaf, left, right = node
            if feat == -1:
                # leaf
                lines.append(f"      case {n_idx}: return {thresh_or_leaf:.8f}f;")
            else:
                lines.append(f"      case {n_idx}: node = (f[{feat}] < {thresh_or_leaf:.8f}f) ? {left} : {right}; break;")
        lines.append(f"      default: return 0.0f;")
        lines.append(f"    }}")
        lines.append(f"  }}")
        lines.append(f"}}")
        lines.append(f"")

    # Main predict function
    lines.append(f"static inline float {name}_predict(const float raw_features[{n_base}]) {{")
    lines.append(f"  float scaled[{n_base}];")
    lines.append(f"  for (int i = 0; i < {n_base}; i++) {{")
    lines.append(f"    scaled[i] = (raw_features[i] - {name}_scaler_mean[i]) / {name}_scaler_scale[i];")
    lines.append(f"  }}")
    lines.append(f"  float sum = {name.upper()}_BASE_SCORE;")
    for t_idx in range(n_trees):
        lines.append(f"  sum += {name}_tree{t_idx}(scaled);")
    lines.append(f"  return sum;")
    lines.append(f"}}")
    lines.append(f"")
    lines.append(f"#endif // MODEL_{name.upper()}_H")

    filepath = HEADER_DIR / filename
    filepath.write_text("\n".join(lines))
    print(f"  -> Exported {filepath} (manual tree export, {n_trees} trees)")


# ═══════════════════════════════════════════════════════════════════════════
#  MODEL 1: SoC PREDICTION (Lasso + Polynomial Features)
# ═══════════════════════════════════════════════════════════════════════════

def load_bmw_trips():
    """Load and preprocess all BMW i3 trip CSVs."""
    trip_files = sorted(BMW_DIR.glob("Trip*.csv"))
    all_data = []

    for f in trip_files:
        df = pd.read_csv(f, sep=';', encoding='latin1')
        trip_name = f.stem
        is_winter = 1 if trip_name.startswith("TripB") else 0

        # Find columns
        col_map = {
            'time': find_col(df, 'Time'),
            'velocity': find_col(df, 'Velocity'),
            'elevation': find_col(df, 'Elevation'),
            'throttle': find_col(df, 'Throttle'),
            'torque': find_col(df, 'Motor Torque') or find_col(df, 'Torque'),
            'accel': find_col(df, 'Longitudinal Accel') or find_col(df, 'Accel'),
            'regen': find_col(df, 'Regenerative'),
            'voltage': find_col(df, 'Battery Voltage') or find_col(df, 'Voltage'),
            'current': find_col(df, 'Battery Current') or find_col(df, 'Current'),
            'btemp': find_col(df, 'Battery Temp'),
            'soc': find_col(df, 'SoC'),
            'heating': find_col(df, 'Heating Power CAN') or find_col(df, 'Heating'),
            'aircon': find_col(df, 'AirCon'),
            'atemp': find_col(df, 'Ambient Temp'),
        }

        if col_map['soc'] is None or col_map['voltage'] is None or col_map['velocity'] is None:
            continue

        # Match notebook: use iloc[0] - iloc[-1] (NaN trips get filtered out)
        soc_first = df[col_map['soc']].iloc[0]
        soc_last = df[col_map['soc']].iloc[-1]
        soc_change = soc_first - soc_last
        if not (soc_change > 2):  # NaN fails this check, matching notebook behavior
            continue

        all_data.append((df, col_map, trip_name, is_winter))

    print(f"  Loaded {len(all_data)} valid BMW i3 trips")
    return all_data


def extract_soc_features(trips):
    """Extract windowed features for SoC prediction."""
    WINDOW = 600
    STRIDE = 200
    BATTERY_KWH = 33.0

    rows = []
    for df, cm, trip_name, is_winter in trips:
        time_col = df[cm['time']].values.astype(float)
        voltage = df[cm['voltage']].values.astype(float)
        current = df[cm['current']].values.astype(float)
        soc = df[cm['soc']].values.astype(float)

        btemp = df[cm['btemp']].values.astype(float) if cm['btemp'] else np.zeros(len(df))
        atemp = df[cm['atemp']].values.astype(float) if cm['atemp'] else np.zeros(len(df))
        vel = df[cm['velocity']].values.astype(float) if cm['velocity'] else np.zeros(len(df))
        accel = df[cm['accel']].values.astype(float) if cm['accel'] else np.zeros(len(df))
        torque = df[cm['torque']].values.astype(float) if cm['torque'] else np.zeros(len(df))
        elev = df[cm['elevation']].values.astype(float) if cm['elevation'] else np.zeros(len(df))

        heating = df[cm['heating']].values.astype(float) if cm['heating'] else np.zeros(len(df))
        aircon = df[cm['aircon']].values.astype(float) if cm['aircon'] else np.zeros(len(df))
        hvac = np.abs(heating) * 1000 + np.abs(aircon) * 1000

        power = voltage * current

        # Cumulative features
        dt = np.diff(time_col, prepend=time_col[0])
        dt[0] = 0
        cum_ah = np.cumsum(current * dt / 3600)
        cum_wh = np.cumsum(power * dt / 3600)
        cum_dist = np.cumsum(np.abs(vel) / 3600 * dt)

        n = len(df)
        for start in range(0, n - WINDOW, STRIDE):
            end = start + WINDOW
            mid = (start + end) // 2

            w_v = voltage[start:end]
            w_i = current[start:end]
            w_p = power[start:end]
            w_vel = vel[start:end]
            w_acc = accel[start:end]
            w_torq = torque[start:end]
            w_bt = btemp[start:end]
            w_at = atemp[start:end]
            w_hvac = hvac[start:end]
            w_elev = elev[start:end]

            rows.append({
                'Avg_Voltage': np.mean(w_v),
                'Avg_Current': np.mean(w_i),
                'Avg_Power': np.mean(w_p),
                'Avg_Velocity': np.mean(w_vel),
                'Avg_Accel': np.mean(w_acc),
                'Avg_Torque': np.mean(w_torq),
                'Avg_Battery_Temp': np.mean(w_bt),
                'Avg_Ambient_Temp': np.mean(w_at),
                'Avg_HVAC': np.mean(w_hvac),
                'Max_Current': np.max(w_i),
                'Min_Current': np.min(w_i),
                'Std_Current': np.std(w_i),
                'Std_Velocity': np.std(w_vel),
                'Max_Power': np.max(w_p),
                'Min_Voltage': np.min(w_v),
                'Cumulative_Ah': cum_ah[mid],
                'Cumulative_Wh': cum_wh[mid],
                'Cumulative_Dist_km': cum_dist[mid],
                'Elapsed_s': time_col[mid] - time_col[0],
                'Elevation_Change': w_elev[-1] - w_elev[0] if len(w_elev) > 0 else 0,
                'Temp_Diff': np.mean(w_bt) - np.mean(w_at),
                'Is_Winter': is_winter,
                'SOC': soc[mid],
                'trip': trip_name,
            })

    return pd.DataFrame(rows)


def train_soc_model():
    """Train SoC model and export as C header."""
    print("\n" + "="*60)
    print("MODEL 1: SoC Prediction (Lasso + Polynomial)")
    print("="*60)

    trips = load_bmw_trips()
    df = extract_soc_features(trips)
    df = df.dropna()
    print(f"  Total windows: {len(df)}")

    feature_cols = [c for c in df.columns if c not in ('SOC', 'trip')]
    X = df[feature_cols].values
    y = df['SOC'].values

    # Trip-level split (matching notebook: train_test_split on trip name list in load order)
    # The notebook passes the trip names in glob-sorted order to train_test_split
    unique_trips = list(dict.fromkeys(df['trip']))  # preserve insertion order (= glob order)
    train_trips_list, test_trips_list = train_test_split(
        unique_trips, test_size=0.25, random_state=42
    )
    train_trips = set(train_trips_list)
    print(f"  Train: {len(train_trips_list)} trips, Test: {len(test_trips_list)} trips")

    train_mask = df['trip'].isin(train_trips)
    X_train, X_test = X[train_mask], X[~train_mask]
    y_train, y_test = y[train_mask], y[~train_mask]

    # Scale
    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    # XGBoost (ESP32-constrained: shallow trees, limited count)
    # The notebook's XGBoost tuned achieved R²≈0.88 on all 22 features
    model = xgb.XGBRegressor(
        n_estimators=100,  # keep small for ESP32
        max_depth=4,
        learning_rate=0.08,
        subsample=0.8,
        colsample_bytree=0.8,
        min_child_weight=8,
        reg_alpha=0.5,
        reg_lambda=2.0,
        tree_method='hist',
        random_state=42,
    )
    model.fit(X_train_s, y_train)

    y_pred = model.predict(X_test_s)
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    print(f"  XGBoost (ESP32-sized) -> R²={r2:.4f}, MAE={mae:.2f}%")

    # Save feature metadata
    meta = {
        'feature_names': feature_cols,
        'scaler_mean': scaler.mean_.tolist(),
        'scaler_scale': scaler.scale_.tolist(),
        'r2': r2, 'mae': mae,
    }
    (OUT_DIR / "soc_meta.json").write_text(json.dumps(meta, indent=2))

    # Export as C header
    if not export_xgb_emlearn_header("soc", model, "model_soc.h"):
        export_xgb_manual_header(
            "soc", model,
            scaler.mean_, scaler.scale_,
            len(feature_cols), "model_soc.h"
        )

    return r2, mae


# ═══════════════════════════════════════════════════════════════════════════
#  MODEL 2: RANGE PREDICTION (XGBoost)
# ═══════════════════════════════════════════════════════════════════════════

def extract_range_features(trips):
    """Extract windowed features for energy consumption / range prediction."""
    WINDOW = 600
    STRIDE = 200
    BATTERY_KWH = 33.0
    MIN_SPEED = 3.0  # km/h
    MIN_DIST = 0.2   # km

    rows = []
    for df, cm, trip_name, is_winter in trips:
        time_col = df[cm['time']].values.astype(float)
        voltage = df[cm['voltage']].values.astype(float)
        current = df[cm['current']].values.astype(float)
        soc = df[cm['soc']].values.astype(float)

        btemp = df[cm['btemp']].values.astype(float) if cm['btemp'] else np.zeros(len(df))
        atemp = df[cm['atemp']].values.astype(float) if cm['atemp'] else np.zeros(len(df))
        vel = df[cm['velocity']].values.astype(float) if cm['velocity'] else np.zeros(len(df))
        accel = df[cm['accel']].values.astype(float) if cm['accel'] else np.zeros(len(df))
        torque = df[cm['torque']].values.astype(float) if cm['torque'] else np.zeros(len(df))
        elev = df[cm['elevation']].values.astype(float) if cm['elevation'] else np.zeros(len(df))
        throttle = df[cm['throttle']].values.astype(float) if cm['throttle'] else np.zeros(len(df))
        regen = df[cm['regen']].values.astype(float) if cm['regen'] else np.zeros(len(df))

        heating = df[cm['heating']].values.astype(float) if cm['heating'] else np.zeros(len(df))
        aircon = df[cm['aircon']].values.astype(float) if cm['aircon'] else np.zeros(len(df))
        hvac = np.abs(heating) * 1000 + np.abs(aircon) * 1000

        power = voltage * current
        dt = np.diff(time_col, prepend=time_col[0])
        dt[0] = 0

        n = len(df)
        for start in range(0, n - WINDOW, STRIDE):
            end = start + WINDOW

            w_soc = soc[start:end]
            w_vel = vel[start:end]
            w_dt = dt[start:end]

            # Filter: must be moving
            avg_speed = np.mean(w_vel)
            if avg_speed < MIN_SPEED:
                continue

            # Distance in this window
            total_dist_km = np.sum(np.abs(w_vel) / 3600 * w_dt)
            if total_dist_km < MIN_DIST:
                continue

            # Energy consumed (from SOC delta)
            soc_delta = w_soc[0] - w_soc[-1]  # positive = discharge
            energy_wh = soc_delta / 100.0 * BATTERY_KWH * 1000
            consumption = energy_wh / total_dist_km  # Wh/km

            if consumption < 20 or consumption > 600:
                continue

            w_v = voltage[start:end]
            w_i = current[start:end]
            w_p = power[start:end]
            w_acc = accel[start:end]
            w_torq = torque[start:end]
            w_bt = btemp[start:end]
            w_at = atemp[start:end]
            w_hvac = hvac[start:end]
            w_elev = elev[start:end]
            w_thr = throttle[start:end]
            w_regen = regen[start:end]
            w_time = time_col[start:end]

            rows.append({
                'SOC': w_soc[0],
                'Voltage_avg': np.mean(w_v),
                'Current_avg': np.mean(w_i),
                'Power_avg': np.mean(w_p),
                'Battery_Temp': np.mean(w_bt),
                'Ambient_Temp': np.mean(w_at),
                'Velocity_avg': np.mean(w_vel),
                'Velocity_std': np.std(w_vel),
                'Velocity_max': np.max(w_vel),
                'Velocity_p25': np.percentile(w_vel, 25),
                'Velocity_p75': np.percentile(w_vel, 75),
                'Accel_avg': np.mean(w_acc),
                'Accel_std': np.std(w_acc),
                'Hard_Brake_pct': np.mean(w_acc < -2.0) * 100,
                'Throttle_avg': np.mean(w_thr),
                'Torque_avg': np.mean(w_torq),
                'Torque_std': np.std(w_torq),
                'Elev_change': w_elev[-1] - w_elev[0],
                'Elev_std': np.std(w_elev),
                'HVAC_power': np.mean(w_hvac),
                'Is_Winter': is_winter,
                'Window_time_s': w_time[-1] - w_time[0],
                'Regen_pct': np.mean(w_regen > 0) * 100 if cm['regen'] else 0,
                'Temp_diff': np.mean(w_bt) - np.mean(w_at),
                'Consumption_Wh_per_km': consumption,
                'trip': trip_name,
            })

    return pd.DataFrame(rows)


def train_range_model():
    """Train range/consumption model (XGBoost) and export."""
    print("\n" + "="*60)
    print("MODEL 2: Range Prediction (XGBoost)")
    print("="*60)

    trips = load_bmw_trips()
    df = extract_range_features(trips)
    df = df.dropna()

    # Clip outliers
    low, high = df['Consumption_Wh_per_km'].quantile([0.02, 0.98])
    df = df[(df['Consumption_Wh_per_km'] >= low) & (df['Consumption_Wh_per_km'] <= high)]
    print(f"  Total windows: {len(df)}")

    feature_cols = [c for c in df.columns if c not in ('Consumption_Wh_per_km', 'trip')]
    X = df[feature_cols].values
    y = df['Consumption_Wh_per_km'].values

    # Trip-level split (matching notebook)
    unique_trips = sorted(df['trip'].unique())
    train_trips_list, test_trips_list = train_test_split(
        unique_trips, test_size=0.25, random_state=42
    )
    train_trips = set(train_trips_list)

    train_mask = df['trip'].isin(train_trips)
    X_train, X_test = X[train_mask], X[~train_mask]
    y_train, y_test = y[train_mask], y[~train_mask]

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    # XGBoost with constrained params for ESP32 (fewer trees, shallow)
    model = xgb.XGBRegressor(
        n_estimators=100,  # keep small for ESP32
        max_depth=4,       # shallow trees
        learning_rate=0.08,
        subsample=0.8,
        colsample_bytree=0.8,
        min_child_weight=10,
        reg_alpha=0.5,
        reg_lambda=2.0,
        tree_method='hist',
        random_state=42,
    )
    model.fit(X_train_s, y_train)

    y_pred = model.predict(X_test_s)
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    print(f"  XGBoost (ESP32-sized) -> R²={r2:.4f}, MAE={mae:.1f} Wh/km")

    # Save metadata
    meta = {
        'feature_names': feature_cols,
        'scaler_mean': scaler.mean_.tolist(),
        'scaler_scale': scaler.scale_.tolist(),
        'r2': r2, 'mae': mae,
    }
    (OUT_DIR / "range_meta.json").write_text(json.dumps(meta, indent=2))

    # Try emlearn first, fallback to manual
    if not export_xgb_emlearn_header("range", model, "model_range.h"):
        export_xgb_manual_header(
            "range", model,
            scaler.mean_, scaler.scale_,
            len(feature_cols), "model_range.h"
        )

    return r2, mae


# ═══════════════════════════════════════════════════════════════════════════
#  MODEL 3: SoH PREDICTION (LassoCV + Polynomial)
# ═══════════════════════════════════════════════════════════════════════════

def load_nasa_data():
    """Load NASA battery dataset with metadata."""
    meta = pd.read_csv(NASA_DIR / "metadata.csv")
    # Coerce non-numeric impedance values to NaN (matching notebook behavior)
    meta['Re'] = pd.to_numeric(meta['Re'], errors='coerce')
    meta['Rct'] = pd.to_numeric(meta['Rct'], errors='coerce')
    meta['Capacity'] = pd.to_numeric(meta['Capacity'], errors='coerce')
    # Sanitize: impedance values should be small positive numbers (< 10 Ohm)
    # Corrupt values in B0050/B0052 (e.g. -9.7e14) → NaN
    meta.loc[meta['Re'].abs() > 10, 'Re'] = np.nan
    meta.loc[meta['Rct'].abs() > 10, 'Rct'] = np.nan
    return meta


def extract_soh_features(meta):
    """Extract per-cycle features for SoH prediction."""
    RATED_CAPACITY = 2.0

    rows = []
    batteries = meta['battery_id'].unique()

    for batt in batteries:
        batt_meta = meta[meta['battery_id'] == batt].sort_values('uid')
        cycle = 0

        # Get impedance values (forward fill)
        impedance_re = []
        impedance_rct = []
        for _, row in batt_meta.iterrows():
            if row['type'] == 'impedance':
                impedance_re.append(row.get('Re', np.nan))
                impedance_rct.append(row.get('Rct', np.nan))
            elif row['type'] == 'discharge':
                cycle += 1
                # Load discharge data
                csv_path = NASA_DIR / "data" / row['filename']
                if not csv_path.exists():
                    continue

                try:
                    ddf = pd.read_csv(csv_path)
                except:
                    continue

                if len(ddf) < 5:
                    continue

                v = ddf['Voltage_measured'].values
                i = ddf['Current_measured'].values
                t = ddf['Temperature_measured'].values
                time_s = ddf['Time'].values

                capacity = row.get('Capacity', np.nan)
                if pd.isna(capacity):
                    continue

                soh = (capacity / RATED_CAPACITY) * 100

                # Get latest impedance
                re_val = impedance_re[-1] if impedance_re else np.nan
                rct_val = impedance_rct[-1] if impedance_rct else np.nan

                # Compute energy
                energy = np.trapz(v * np.abs(i), time_s) / 3600 if len(time_s) > 1 else 0

                rows.append({
                    'battery_id': batt,
                    'cycle': cycle,
                    'v_mean': np.mean(v), 'v_std': np.std(v),
                    'v_min': np.min(v), 'v_max': np.max(v),
                    'v_range': np.max(v) - np.min(v),
                    'i_mean': np.mean(i), 'i_std': np.std(i),
                    'i_min': np.min(i), 'i_max': np.max(i),
                    't_mean': np.mean(t), 't_std': np.std(t),
                    't_max': np.max(t), 't_rise': np.max(t) - t[0],
                    'discharge_time': time_s[-1] if len(time_s) > 0 else 0,
                    'energy': energy,
                    'Re': re_val, 'Rct': rct_val,
                    'SoH': soh,
                    'capacity': capacity,
                })

    df = pd.DataFrame(rows)
    # Forward/back fill impedance within each battery
    df['Re'] = df.groupby('battery_id')['Re'].ffill().bfill()
    df['Rct'] = df.groupby('battery_id')['Rct'].ffill().bfill()
    df = df.dropna()

    print(f"  Total cycles: {len(df)}, batteries: {df['battery_id'].nunique()}")
    return df


def train_soh_model():
    """Train SoH model (LassoCV + Poly) and export."""
    print("\n" + "="*60)
    print("MODEL 3: SoH Prediction (LassoCV + Polynomial)")
    print("="*60)

    meta = load_nasa_data()
    df = extract_soh_features(meta)

    feature_cols = ['cycle', 'v_mean', 'v_std', 'v_min', 'v_max', 'v_range',
                    'i_mean', 'i_std', 'i_min', 'i_max',
                    't_mean', 't_std', 't_max', 't_rise',
                    'discharge_time', 'energy', 'Re', 'Rct']

    X = df[feature_cols].values
    y = df['SoH'].values
    groups = df['battery_id'].values

    # Cross-battery split: classic batteries for test
    classic = {'B0005', 'B0006', 'B0007', 'B0018'}
    test_mask = df['battery_id'].isin(classic)
    X_train, X_test = X[~test_mask], X[test_mask]
    y_train, y_test = y[~test_mask], y[test_mask]
    groups_train = df[~test_mask]['battery_id'].values

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    # Top 10 by correlation
    correlations = np.array([abs(np.corrcoef(X_train_s[:, i], y_train)[0, 1])
                             for i in range(X_train_s.shape[1])])
    top_idx = np.argsort(correlations)[-10:][::-1]
    top_names = [feature_cols[i] for i in top_idx]
    print(f"  Top 10 features: {top_names}")

    poly = PolynomialFeatures(degree=2, include_bias=False)
    X_train_poly = poly.fit_transform(X_train_s[:, top_idx])
    X_test_poly = poly.transform(X_test_s[:, top_idx])

    gkf = GroupKFold(n_splits=5)
    model = LassoCV(alphas=np.logspace(-4, 2, 50), max_iter=10000,
                     cv=gkf.split(X_train_poly, y_train, groups_train), random_state=42)
    model.fit(X_train_poly, y_train)

    y_pred = model.predict(X_test_poly)
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    print(f"  LassoCV Poly -> R²={r2:.4f}, MAE={mae:.2f}%, alpha={model.alpha_:.4f}")

    meta_out = {
        'feature_names': feature_cols,
        'top_feature_indices': top_idx.tolist(),
        'top_feature_names': top_names,
        'scaler_mean': scaler.mean_.tolist(),
        'scaler_scale': scaler.scale_.tolist(),
        'r2': r2, 'mae': mae,
    }
    (OUT_DIR / "soh_meta.json").write_text(json.dumps(meta_out, indent=2))

    poly_powers = poly.powers_.astype(int)
    export_linear_model_header(
        name="soh",
        weights=model.coef_,
        bias=model.intercept_,
        scaler_mean=scaler.mean_[top_idx],
        scaler_scale=scaler.scale_[top_idx],
        feature_names=top_names,
        filename="model_soh.h",
        poly_powers=poly_powers,
    )

    return r2, mae


# ═══════════════════════════════════════════════════════════════════════════
#  MODEL 4: RUL PREDICTION (RidgeCV — linear, 42 features)
# ═══════════════════════════════════════════════════════════════════════════

def _extract_base_features_for_battery(meta_df, battery_id):
    """Extract per-cycle features for one battery (matches notebook exactly)."""
    dis = meta_df[(meta_df.battery_id == battery_id) &
                  (meta_df.type == 'discharge') &
                  (meta_df.Capacity.notna())]
    imp = meta_df[(meta_df.battery_id == battery_id) &
                  (meta_df.type == 'impedance')]

    features = []
    for idx, (_, row) in enumerate(dis.iterrows()):
        csv_path = NASA_DIR / "data" / row['filename']
        try:
            ddf = pd.read_csv(csv_path)
        except:
            continue

        v = ddf['Voltage_measured'].values
        i = ddf['Current_measured'].values
        t = ddf['Temperature_measured'].values
        time_s = ddf['Time'].values

        # Impedance: use last impedance measurement BEFORE this discharge (by uid)
        prior_imp = imp[imp.uid < row['uid']]
        if len(prior_imp) > 0:
            last_imp = prior_imp.iloc[-1]
            re_val = last_imp['Re'] if pd.notna(last_imp['Re']) else np.nan
            rct_val = last_imp['Rct'] if pd.notna(last_imp['Rct']) else np.nan
        else:
            re_val = np.nan
            rct_val = np.nan

        features.append({
            'battery_id': battery_id,
            'cycle': idx,  # 0-based, matching notebook
            'capacity': row['Capacity'],
            'v_mean': np.mean(v), 'v_std': np.std(v),
            'v_min': np.min(v), 'v_max': np.max(v),
            'v_range': np.max(v) - np.min(v),
            'i_mean': np.mean(i), 'i_std': np.std(i),
            'i_min': np.min(i), 'i_max': np.max(i),
            't_mean': np.mean(t), 't_std': np.std(t),
            't_max': np.max(t), 't_rise': np.max(t) - t[0],
            'discharge_time': time_s[-1] if len(time_s) > 0 else 0,
            'energy': np.trapz(v * np.abs(i), time_s) / 3600 if len(time_s) > 1 else 0,
            'Re': re_val, 'Rct': rct_val,
        })
    return pd.DataFrame(features)


def extract_rul_features(meta):
    """Extract per-cycle features for RUL prediction (matches notebook pipeline)."""
    RATED_CAPACITY = 2.0
    EOL_THRESHOLD = 1.4

    # Step 1: Extract base features per battery
    all_frames = []
    for batt in sorted(meta['battery_id'].unique()):
        bdf = _extract_base_features_for_battery(meta, batt)
        if len(bdf) > 0:
            all_frames.append(bdf)
    df = pd.concat(all_frames, ignore_index=True)

    # Step 2: Add RUL and SoH
    result = []
    for bid in df.battery_id.unique():
        bdf = df[df.battery_id == bid].copy()
        eol_rows = bdf[bdf.capacity <= EOL_THRESHOLD]
        if len(eol_rows) > 0:
            eol_cycle = eol_rows.iloc[0]['cycle']
        else:
            eol_cycle = bdf['cycle'].max()
        bdf['RUL'] = eol_cycle - bdf['cycle']
        bdf['SoH'] = bdf['capacity'] / RATED_CAPACITY * 100
        result.append(bdf)
    df = pd.concat(result, ignore_index=True)

    # Step 3: Remove post-EOL samples
    pre_clip = len(df)
    df = df[df.RUL >= 0].copy()
    print(f"  Removed {pre_clip - len(df)} post-EOL samples")

    # Step 4: Handle missing impedance (ffill then bfill, matching notebook)
    df['Re'] = df.groupby('battery_id')['Re'].ffill()
    df['Rct'] = df.groupby('battery_id')['Rct'].bfill()
    df['Re'] = df.groupby('battery_id')['Re'].bfill()
    df['Rct'] = df.groupby('battery_id')['Rct'].bfill()
    df = df.dropna(subset=['Re', 'Rct'])

    # Step 5: Degradation features (matching notebook exactly)
    for w in [3, 5]:
        df[f'cap_roll{w}'] = df.groupby('battery_id')['capacity'].transform(
            lambda x: x.rolling(w, min_periods=1).mean())
        df[f'cap_std{w}'] = df.groupby('battery_id')['capacity'].transform(
            lambda x: x.rolling(w, min_periods=1).std().fillna(0))

    df['SoH_delta'] = df.groupby('battery_id')['SoH'].diff().fillna(0)
    df['cap_delta'] = df.groupby('battery_id')['capacity'].diff().fillna(0)
    df['Re_delta'] = df.groupby('battery_id')['Re'].diff().fillna(0)
    df['energy_delta'] = df.groupby('battery_id')['energy'].diff().fillna(0)

    df['SoH_rate'] = df.groupby('battery_id', group_keys=False).apply(
        lambda g: (g['SoH'].iloc[0] - g['SoH']) / (g['cycle'] - g['cycle'].iloc[0] + 1)
    ).reset_index(level=0, drop=True) if False else np.nan  # placeholder
    # Manual SoH_rate to avoid groupby.apply issues
    soh_rate = []
    for bid in df.battery_id.unique():
        mask = df.battery_id == bid
        g = df[mask]
        first_soh = g['SoH'].iloc[0]
        first_cycle = g['cycle'].iloc[0]
        soh_rate.append((first_soh - g['SoH']) / (g['cycle'] - first_cycle + 1))
    df['SoH_rate'] = pd.concat(soh_rate)

    df['cap_fade'] = df.groupby('battery_id')['capacity'].transform(
        lambda x: (x.iloc[0] - x) / x.iloc[0])

    # Lag features
    for lag in [1, 2, 3]:
        df[f'SoH_lag{lag}'] = df.groupby('battery_id')['SoH'].shift(lag)
        df[f'cap_lag{lag}'] = df.groupby('battery_id')['capacity'].shift(lag)
        if lag <= 2:
            df[f'Re_lag{lag}'] = df.groupby('battery_id')['Re'].shift(lag)

    for lag in [1, 2, 3]:
        df[f'SoH_lag{lag}'] = df[f'SoH_lag{lag}'].fillna(df['SoH'])
        df[f'cap_lag{lag}'] = df[f'cap_lag{lag}'].fillna(df['capacity'])
        if lag <= 2:
            df[f'Re_lag{lag}'] = df[f'Re_lag{lag}'].fillna(df['Re'])

    # Interaction features
    df['SoH_x_rate'] = df['SoH'] * df['SoH_rate']
    df['SoH_x_delta'] = df['SoH'] * df['SoH_delta']
    df['cap_x_Re'] = df['capacity'] * df['Re']
    df['SoH_sq'] = df['SoH'] ** 2
    df['cap_fade_sq'] = df['cap_fade'] ** 2

    df = df.dropna()
    print(f"  Total cycles (RUL): {len(df)}, batteries: {df['battery_id'].nunique()}")
    return df


def train_rul_model():
    """Train RUL model (RidgeCV — linear) and export."""
    print("\n" + "="*60)
    print("MODEL 4: RUL Prediction (RidgeCV)")
    print("="*60)

    meta = load_nasa_data()
    df = extract_rul_features(meta)

    # Exact feature list matching notebook
    feature_cols = ['cycle', 'SoH', 'v_mean', 'v_std', 'v_min', 'v_max', 'v_range',
                    'i_mean', 'i_std', 'i_min', 'i_max',
                    't_mean', 't_std', 't_max', 't_rise',
                    'discharge_time', 'energy', 'Re', 'Rct',
                    'SoH_delta', 'cap_delta', 'Re_delta', 'energy_delta',
                    'SoH_rate', 'cap_fade',
                    'cap_roll3', 'cap_roll5', 'cap_std3', 'cap_std5',
                    'SoH_lag1', 'SoH_lag2', 'SoH_lag3',
                    'cap_lag1', 'cap_lag2', 'cap_lag3',
                    'Re_lag1', 'Re_lag2',
                    'SoH_x_rate', 'SoH_x_delta', 'cap_x_Re',
                    'SoH_sq', 'cap_fade_sq']

    X = df[feature_cols].values
    y = df['RUL'].values

    # Hybrid temporal split (matching notebook exactly)
    classic = ['B0005', 'B0006', 'B0007', 'B0018']
    train_rows, test_rows = [], []
    for bid in sorted(df.battery_id.unique()):
        bdf = df[df.battery_id == bid].sort_values('cycle')
        if bid in classic:
            n = len(bdf)
            split = int(n * 0.7)
            train_rows.append(bdf.iloc[:split])
            test_rows.append(bdf.iloc[split:])
        else:
            train_rows.append(bdf)

    train_df = pd.concat(train_rows, ignore_index=True)
    test_df = pd.concat(test_rows, ignore_index=True)
    print(f"  Train: {len(train_df)} samples, Test: {len(test_df)} samples")

    X_train = train_df[feature_cols].values
    y_train = train_df['RUL'].values
    X_test = test_df[feature_cols].values
    y_test = test_df['RUL'].values

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s = scaler.transform(X_test)

    model = RidgeCV(alphas=np.logspace(-2, 4, 50))
    model.fit(X_train_s, y_train)

    y_pred = model.predict(X_test_s)
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    print(f"  RidgeCV -> R²={r2:.4f}, MAE={mae:.1f} cycles, alpha={model.alpha_:.4f}")

    meta_out = {
        'feature_names': feature_cols,
        'scaler_mean': scaler.mean_.tolist(),
        'scaler_scale': scaler.scale_.tolist(),
        'r2': r2, 'mae': mae,
        'n_features': len(feature_cols),
    }
    (OUT_DIR / "rul_meta.json").write_text(json.dumps(meta_out, indent=2))

    export_linear_model_header(
        name="rul",
        weights=model.coef_,
        bias=model.intercept_,
        scaler_mean=scaler.mean_,
        scaler_scale=scaler.scale_,
        feature_names=feature_cols,
        filename="model_rul.h",
        poly_powers=None,
    )

    return r2, mae


# ═══════════════════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("CyphEV — Training models for ESP32 deployment")
    print("=" * 60)

    results = {}

    r2, mae = train_soc_model()
    results['SoC'] = {'R²': round(r2, 4), 'MAE': f"{mae:.2f}%"}

    r2, mae = train_range_model()
    results['Range'] = {'R²': round(r2, 4), 'MAE': f"{mae:.1f} Wh/km"}

    r2, mae = train_soh_model()
    results['SoH'] = {'R²': round(r2, 4), 'MAE': f"{mae:.2f}%"}

    r2, mae = train_rul_model()
    results['RUL'] = {'R²': round(r2, 4), 'MAE': f"{mae:.1f} cycles"}

    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    for name, metrics in results.items():
        print(f"  {name:10s}  R²={metrics['R²']:.4f}  MAE={metrics['MAE']}")

    print(f"\nC headers exported to: {HEADER_DIR}")
    print("Run the ESP32 firmware with these headers to deploy!")
